title: Universal
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
logo: images/logo.svg
docs_url: 'https://docs.stackbit.com'
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
